DROP TABLE dbo.tickets;
DROP TABLE dbo.users;
DROP TABLE dbo.acticles;
DROP TABLE dbo.categories;
DROP TABLE dbo.services;
DROP TABLE dbo.priorities;
DROP TABLE dbo.statuses;
DROP TABLE dbo.supporters;
DROP DATABASE Knowledge;